import 'package:gravity_habit/domain/entities/achievement.dart';

class AchievementCatalog {
  AchievementCatalog._();

  static const all = <AchievementDef>[
    // ---- CONSISTENCY (30) ----
    AchievementDef(id: 'C1', name: 'First Light', description: 'Complete your first habit', rarity: AchievementRarity.common, stardustReward: 5, group: 'Consistency', criteria: AchievementCriteria(totalCompletions: 1)),
    AchievementDef(id: 'C2', name: 'Three in a Row', description: 'Reach a 3-day streak', rarity: AchievementRarity.common, stardustReward: 5, group: 'Consistency', criteria: AchievementCriteria(streakDays: 3)),
    AchievementDef(id: 'C3', name: 'Week One', description: 'Reach a 7-day streak', rarity: AchievementRarity.common, stardustReward: 5, group: 'Consistency', criteria: AchievementCriteria(streakDays: 7)),
    AchievementDef(id: 'C4', name: 'Steady Hand', description: 'Reach a 14-day streak', rarity: AchievementRarity.rare, stardustReward: 25, group: 'Consistency', criteria: AchievementCriteria(streakDays: 14)),
    AchievementDef(id: 'C5', name: 'Habit Born', description: 'Reach a 21-day streak', rarity: AchievementRarity.rare, stardustReward: 25, group: 'Consistency', criteria: AchievementCriteria(streakDays: 21)),
    AchievementDef(id: 'C6', name: 'Lunar Loop', description: 'Reach a 30-day streak', rarity: AchievementRarity.rare, stardustReward: 25, group: 'Consistency', criteria: AchievementCriteria(streakDays: 30)),
    AchievementDef(id: 'C7', name: 'Quarterly', description: 'Reach a 90-day streak', rarity: AchievementRarity.epic, stardustReward: 100, group: 'Consistency', criteria: AchievementCriteria(streakDays: 90)),
    AchievementDef(id: 'C8', name: 'Centurion', description: 'Reach a 100-day streak', rarity: AchievementRarity.epic, stardustReward: 100, group: 'Consistency', criteria: AchievementCriteria(streakDays: 100)),
    AchievementDef(id: 'C9', name: 'Half a Year', description: 'Reach a 180-day streak', rarity: AchievementRarity.epic, stardustReward: 100, group: 'Consistency', criteria: AchievementCriteria(streakDays: 180)),
    AchievementDef(id: 'C10', name: 'Year of Light', description: 'Reach a 365-day streak', rarity: AchievementRarity.legendary, stardustReward: 250, group: 'Consistency', criteria: AchievementCriteria(streakDays: 365)),
    AchievementDef(id: 'C11', name: 'Beyond Years', description: 'Reach a 500-day streak', rarity: AchievementRarity.legendary, stardustReward: 250, group: 'Consistency', criteria: AchievementCriteria(streakDays: 500)),
    AchievementDef(id: 'C12', name: 'Two Year Voyager', description: 'Reach a 730-day streak', rarity: AchievementRarity.legendary, stardustReward: 250, group: 'Consistency', criteria: AchievementCriteria(streakDays: 730)),
    AchievementDef(id: 'C13', name: 'Millennium Mind', description: 'Reach a 1000-day streak', rarity: AchievementRarity.mythic, stardustReward: 1000, group: 'Consistency', criteria: AchievementCriteria(streakDays: 1000)),
    AchievementDef(id: 'C14', name: 'Perfect Day', description: 'Complete all habits in a single day', rarity: AchievementRarity.common, stardustReward: 5, group: 'Consistency', criteria: AchievementCriteria(perfectDays: 1)),
    AchievementDef(id: 'C15', name: 'Perfect Week', description: 'Complete all habits every day for a week', rarity: AchievementRarity.rare, stardustReward: 25, group: 'Consistency', criteria: AchievementCriteria(perfectWeeks: 1)),
    AchievementDef(id: 'C16', name: 'Perfect Month', description: 'Complete all habits every day for a month', rarity: AchievementRarity.epic, stardustReward: 100, group: 'Consistency', criteria: AchievementCriteria(perfectMonths: 1)),
    AchievementDef(id: 'C17', name: 'Perfect Quarter', description: '90 consecutive perfect days', rarity: AchievementRarity.legendary, stardustReward: 250, group: 'Consistency', criteria: AchievementCriteria(perfectDays: 90)),
    AchievementDef(id: 'C18', name: 'Perfect Year', description: '365 consecutive perfect days', rarity: AchievementRarity.mythic, stardustReward: 1000, group: 'Consistency', criteria: AchievementCriteria(perfectDays: 365)),
    AchievementDef(id: 'C19', name: 'Morning Star', description: 'Complete a habit before 7 AM', rarity: AchievementRarity.common, stardustReward: 5, group: 'Consistency', criteria: AchievementCriteria(customCheck: 'morning_completion')),
    AchievementDef(id: 'C20', name: 'Sunrise Five', description: 'Complete 5 habits before 9 AM', rarity: AchievementRarity.rare, stardustReward: 25, group: 'Consistency', criteria: AchievementCriteria(customCheck: 'sunrise_five')),
    AchievementDef(id: 'C21', name: 'Night Owl', description: 'Complete a habit after 10 PM', rarity: AchievementRarity.common, stardustReward: 5, group: 'Consistency', criteria: AchievementCriteria(customCheck: 'night_owl')),
    AchievementDef(id: 'C22', name: 'Eclipse', description: 'Complete habits both before 7 AM and after 10 PM', rarity: AchievementRarity.rare, stardustReward: 25, group: 'Consistency', criteria: AchievementCriteria(customCheck: 'eclipse')),
    AchievementDef(id: 'C23', name: 'Weekend Warrior', description: 'Complete all habits on a Saturday and Sunday', rarity: AchievementRarity.rare, stardustReward: 25, group: 'Consistency', criteria: AchievementCriteria(customCheck: 'weekend_warrior')),
    AchievementDef(id: 'C24', name: 'Weekday Engine', description: 'Complete all habits Monday through Friday', rarity: AchievementRarity.rare, stardustReward: 25, group: 'Consistency', criteria: AchievementCriteria(customCheck: 'weekday_engine')),
    AchievementDef(id: 'C25', name: 'Holiday Spirit', description: 'Complete all habits on a public holiday', rarity: AchievementRarity.epic, stardustReward: 100, group: 'Consistency', criteria: AchievementCriteria(customCheck: 'holiday_spirit')),
    AchievementDef(id: 'C26', name: 'Birthday Promise', description: 'Complete all habits on your app install anniversary', rarity: AchievementRarity.epic, stardustReward: 100, group: 'Consistency', criteria: AchievementCriteria(customCheck: 'birthday_promise')),
    AchievementDef(id: 'C27', name: 'Travel-Proof', description: 'Use skip-traveling on 5 different days and return', rarity: AchievementRarity.epic, stardustReward: 100, group: 'Consistency', criteria: AchievementCriteria(customCheck: 'travel_proof')),
    AchievementDef(id: 'C28', name: 'Sick Day Hero', description: 'Return from sick-skip and maintain momentum', rarity: AchievementRarity.rare, stardustReward: 25, group: 'Consistency', criteria: AchievementCriteria(customCheck: 'sick_day_hero')),
    AchievementDef(id: 'C29', name: 'Rain or Shine', description: 'Complete habits for 60 consecutive days', rarity: AchievementRarity.epic, stardustReward: 100, group: 'Consistency', criteria: AchievementCriteria(streakDays: 60)),
    AchievementDef(id: 'C30', name: 'Gravity Itself', description: 'Reach Tier 100', rarity: AchievementRarity.mythic, stardustReward: 1000, group: 'Consistency', criteria: AchievementCriteria(tier: 100)),

    // ---- VARIETY (25) ----
    AchievementDef(id: 'V1', name: 'Diverse Orbit', description: 'Have 3 active habits', rarity: AchievementRarity.common, stardustReward: 5, group: 'Variety', criteria: AchievementCriteria(activeHabits: 3)),
    AchievementDef(id: 'V2', name: 'Constellation', description: 'Have 5 active habits', rarity: AchievementRarity.rare, stardustReward: 25, group: 'Variety', criteria: AchievementCriteria(activeHabits: 5)),
    AchievementDef(id: 'V3', name: 'Solar System', description: 'Have 8 active habits', rarity: AchievementRarity.epic, stardustReward: 100, group: 'Variety', criteria: AchievementCriteria(activeHabits: 8)),
    AchievementDef(id: 'V4', name: 'Galaxy', description: 'Have 12 active habits', rarity: AchievementRarity.legendary, stardustReward: 250, group: 'Variety', criteria: AchievementCriteria(activeHabits: 12)),
    AchievementDef(id: 'V5', name: 'Universe', description: 'Have 20 active habits', rarity: AchievementRarity.mythic, stardustReward: 1000, group: 'Variety', criteria: AchievementCriteria(activeHabits: 20)),
    AchievementDef(id: 'V6', name: 'Body Worker', description: 'Have an active Body habit', rarity: AchievementRarity.common, stardustReward: 5, group: 'Variety', criteria: AchievementCriteria(customCheck: 'body_category')),
    AchievementDef(id: 'V7', name: 'Mind Tender', description: 'Have an active Mind habit', rarity: AchievementRarity.common, stardustReward: 5, group: 'Variety', criteria: AchievementCriteria(customCheck: 'mind_category')),
    AchievementDef(id: 'V8', name: 'Spirit Keeper', description: 'Have an active Spirit habit', rarity: AchievementRarity.common, stardustReward: 5, group: 'Variety', criteria: AchievementCriteria(customCheck: 'spirit_category')),
    AchievementDef(id: 'V9', name: 'Maker', description: 'Have an active Creative habit', rarity: AchievementRarity.common, stardustReward: 5, group: 'Variety', criteria: AchievementCriteria(customCheck: 'creative_category')),
    AchievementDef(id: 'V10', name: 'Connector', description: 'Have an active Connection habit', rarity: AchievementRarity.common, stardustReward: 5, group: 'Variety', criteria: AchievementCriteria(customCheck: 'connection_category')),
    AchievementDef(id: 'V11', name: 'Renaissance', description: 'Have habits in 5+ categories', rarity: AchievementRarity.epic, stardustReward: 100, group: 'Variety', criteria: AchievementCriteria(categoriesUsed: 5)),
    AchievementDef(id: 'V12', name: 'Polymath', description: 'Have habits in all categories', rarity: AchievementRarity.legendary, stardustReward: 250, group: 'Variety', criteria: AchievementCriteria(categoriesUsed: 8)),
    AchievementDef(id: 'V13', name: 'Featherweight', description: 'Complete 50 Feather habits', rarity: AchievementRarity.common, stardustReward: 5, group: 'Variety', criteria: AchievementCriteria(customCheck: 'feather_50')),
    AchievementDef(id: 'V14', name: 'Stone Mason', description: 'Complete 50 Stone habits', rarity: AchievementRarity.rare, stardustReward: 25, group: 'Variety', criteria: AchievementCriteria(customCheck: 'stone_50')),
    AchievementDef(id: 'V15', name: 'Boulder Bearer', description: 'Complete 50 Boulder habits', rarity: AchievementRarity.epic, stardustReward: 100, group: 'Variety', criteria: AchievementCriteria(customCheck: 'boulder_50')),
    AchievementDef(id: 'V16', name: 'Planetary Will', description: 'Complete 50 Planet habits', rarity: AchievementRarity.legendary, stardustReward: 250, group: 'Variety', criteria: AchievementCriteria(customCheck: 'planet_50')),
    AchievementDef(id: 'V17', name: 'Customizer', description: 'Edit a habit for the first time', rarity: AchievementRarity.common, stardustReward: 5, group: 'Variety', criteria: AchievementCriteria(customCheck: 'first_edit')),
    AchievementDef(id: 'V18', name: 'Template Explorer', description: 'Use 5 different templates', rarity: AchievementRarity.rare, stardustReward: 25, group: 'Variety', criteria: AchievementCriteria(customCheck: 'templates_5')),
    AchievementDef(id: 'V19', name: 'Color Curator', description: 'Use 5 different habit colors', rarity: AchievementRarity.common, stardustReward: 5, group: 'Variety', criteria: AchievementCriteria(customCheck: 'colors_5')),
    AchievementDef(id: 'V20', name: 'Emoji Storyteller', description: 'Use 10 different emojis', rarity: AchievementRarity.rare, stardustReward: 25, group: 'Variety', criteria: AchievementCriteria(customCheck: 'emojis_10')),
    AchievementDef(id: 'V21', name: 'Stacker', description: 'Complete 2 habits within 10 minutes', rarity: AchievementRarity.common, stardustReward: 5, group: 'Variety', criteria: AchievementCriteria(customCheck: 'stack_2')),
    AchievementDef(id: 'V22', name: 'Chain Builder', description: 'Complete 3 linked habits in sequence', rarity: AchievementRarity.rare, stardustReward: 25, group: 'Variety', criteria: AchievementCriteria(customCheck: 'chain_3')),
    AchievementDef(id: 'V23', name: 'Architect', description: 'Complete 4+ linked habits in sequence', rarity: AchievementRarity.epic, stardustReward: 100, group: 'Variety', criteria: AchievementCriteria(customCheck: 'chain_4')),
    AchievementDef(id: 'V24', name: 'Why-Writer', description: 'Write a Why for a habit', rarity: AchievementRarity.common, stardustReward: 5, group: 'Variety', criteria: AchievementCriteria(customCheck: 'why_written')),
    AchievementDef(id: 'V25', name: 'Cue Master', description: 'Write a cue for 3 habits', rarity: AchievementRarity.rare, stardustReward: 25, group: 'Variety', criteria: AchievementCriteria(customCheck: 'cues_3')),

    // ---- ENDURANCE (20) ----
    AchievementDef(id: 'E1', name: 'First 100', description: '100 total completions', rarity: AchievementRarity.common, stardustReward: 5, group: 'Endurance', criteria: AchievementCriteria(totalCompletions: 100)),
    AchievementDef(id: 'E2', name: 'Quarter Thousand', description: '250 total completions', rarity: AchievementRarity.rare, stardustReward: 25, group: 'Endurance', criteria: AchievementCriteria(totalCompletions: 250)),
    AchievementDef(id: 'E3', name: 'Half a Thousand', description: '500 total completions', rarity: AchievementRarity.rare, stardustReward: 25, group: 'Endurance', criteria: AchievementCriteria(totalCompletions: 500)),
    AchievementDef(id: 'E4', name: 'Thousand Acts', description: '1000 total completions', rarity: AchievementRarity.epic, stardustReward: 100, group: 'Endurance', criteria: AchievementCriteria(totalCompletions: 1000)),
    AchievementDef(id: 'E5', name: 'Five Thousand', description: '5000 total completions', rarity: AchievementRarity.epic, stardustReward: 100, group: 'Endurance', criteria: AchievementCriteria(totalCompletions: 5000)),
    AchievementDef(id: 'E6', name: 'Ten Thousand Hours', description: '10000 total completions', rarity: AchievementRarity.legendary, stardustReward: 250, group: 'Endurance', criteria: AchievementCriteria(totalCompletions: 10000)),
    AchievementDef(id: 'E7', name: 'Twenty-Five K', description: '25000 total completions', rarity: AchievementRarity.legendary, stardustReward: 250, group: 'Endurance', criteria: AchievementCriteria(totalCompletions: 25000)),
    AchievementDef(id: 'E8', name: 'Fifty Thousand', description: '50000 total completions', rarity: AchievementRarity.mythic, stardustReward: 1000, group: 'Endurance', criteria: AchievementCriteria(totalCompletions: 50000)),
    AchievementDef(id: 'E9', name: 'First Mass', description: 'Accumulate 100 mass', rarity: AchievementRarity.common, stardustReward: 5, group: 'Endurance', criteria: AchievementCriteria(totalMass: 100)),
    AchievementDef(id: 'E10', name: 'Heavy Heart', description: 'Accumulate 1000 mass', rarity: AchievementRarity.rare, stardustReward: 25, group: 'Endurance', criteria: AchievementCriteria(totalMass: 1000)),
    AchievementDef(id: 'E11', name: 'Anchored', description: 'Accumulate 5000 mass', rarity: AchievementRarity.epic, stardustReward: 100, group: 'Endurance', criteria: AchievementCriteria(totalMass: 5000)),
    AchievementDef(id: 'E12', name: 'Immovable', description: 'Accumulate 25000 mass', rarity: AchievementRarity.legendary, stardustReward: 250, group: 'Endurance', criteria: AchievementCriteria(totalMass: 25000)),
    AchievementDef(id: 'E13', name: 'Cosmic Weight', description: 'Accumulate 100000 mass', rarity: AchievementRarity.mythic, stardustReward: 1000, group: 'Endurance', criteria: AchievementCriteria(totalMass: 100000)),
    AchievementDef(id: 'E14', name: 'Marathon Mind', description: 'Use the app for 100 days', rarity: AchievementRarity.epic, stardustReward: 100, group: 'Endurance', criteria: AchievementCriteria(daysInstalled: 100)),
    AchievementDef(id: 'E15', name: 'Year One', description: 'Use the app for 365 days', rarity: AchievementRarity.epic, stardustReward: 100, group: 'Endurance', criteria: AchievementCriteria(daysInstalled: 365)),
    AchievementDef(id: 'E16', name: 'Year Two', description: 'Use the app for 730 days', rarity: AchievementRarity.legendary, stardustReward: 250, group: 'Endurance', criteria: AchievementCriteria(daysInstalled: 730)),
    AchievementDef(id: 'E17', name: 'Year Five', description: 'Use the app for 1825 days', rarity: AchievementRarity.mythic, stardustReward: 1000, group: 'Endurance', criteria: AchievementCriteria(daysInstalled: 1825)),
    AchievementDef(id: 'E18', name: 'Long Game', description: 'Maintain 5+ habits for 90 days', rarity: AchievementRarity.legendary, stardustReward: 250, group: 'Endurance', criteria: AchievementCriteria(customCheck: 'long_game')),
    AchievementDef(id: 'E19', name: 'Patient Builder', description: 'Reach Tier 50', rarity: AchievementRarity.epic, stardustReward: 100, group: 'Endurance', criteria: AchievementCriteria(tier: 50)),
    AchievementDef(id: 'E20', name: 'Geological Time', description: 'Accumulate 1,000,000 mass', rarity: AchievementRarity.mythic, stardustReward: 1000, group: 'Endurance', criteria: AchievementCriteria(totalMass: 1000000)),

    // ---- RECOVERY (15) ----
    AchievementDef(id: 'R1', name: 'Phoenix', description: 'Return after missing a day', rarity: AchievementRarity.common, stardustReward: 5, group: 'Recovery', criteria: AchievementCriteria(recoveries: 1)),
    AchievementDef(id: 'R2', name: 'Comeback', description: 'Return after missing 3+ days', rarity: AchievementRarity.rare, stardustReward: 25, group: 'Recovery', criteria: AchievementCriteria(customCheck: 'comeback_3')),
    AchievementDef(id: 'R3', name: 'Resurrection', description: 'Return after missing 7+ days', rarity: AchievementRarity.epic, stardustReward: 100, group: 'Recovery', criteria: AchievementCriteria(customCheck: 'comeback_7')),
    AchievementDef(id: 'R4', name: 'Forgiver', description: 'Skip a habit with a reason', rarity: AchievementRarity.common, stardustReward: 5, group: 'Recovery', criteria: AchievementCriteria(customCheck: 'first_skip')),
    AchievementDef(id: 'R5', name: 'Honest Voyager', description: 'Skip 10 habits with reasons', rarity: AchievementRarity.rare, stardustReward: 25, group: 'Recovery', criteria: AchievementCriteria(customCheck: 'skips_10')),
    AchievementDef(id: 'R6', name: 'Freeze Saved', description: 'Have a streak saved by freeze', rarity: AchievementRarity.common, stardustReward: 5, group: 'Recovery', criteria: AchievementCriteria(customCheck: 'freeze_saved')),
    AchievementDef(id: 'R7', name: 'Defrosted', description: 'Return after a freeze and continue the streak', rarity: AchievementRarity.rare, stardustReward: 25, group: 'Recovery', criteria: AchievementCriteria(customCheck: 'defrosted')),
    AchievementDef(id: 'R8', name: 'Bounce Back', description: 'Complete a recovery quest', rarity: AchievementRarity.rare, stardustReward: 25, group: 'Recovery', criteria: AchievementCriteria(customCheck: 'recovery_quest')),
    AchievementDef(id: 'R9', name: 'Resilient', description: 'Complete 5 recovery quests', rarity: AchievementRarity.epic, stardustReward: 100, group: 'Recovery', criteria: AchievementCriteria(customCheck: 'recovery_5')),
    AchievementDef(id: 'R10', name: 'Anti-Fragile', description: 'Recover and surpass previous streak', rarity: AchievementRarity.epic, stardustReward: 100, group: 'Recovery', criteria: AchievementCriteria(customCheck: 'anti_fragile')),
    AchievementDef(id: 'R11', name: 'Mountain Path', description: 'Have 3 different recovery arcs', rarity: AchievementRarity.rare, stardustReward: 25, group: 'Recovery', criteria: AchievementCriteria(recoveries: 3)),
    AchievementDef(id: 'R12', name: 'Storm Walker', description: 'Have 10 recovery arcs', rarity: AchievementRarity.epic, stardustReward: 100, group: 'Recovery', criteria: AchievementCriteria(recoveries: 10)),
    AchievementDef(id: 'R13', name: 'Quiet Strength', description: 'Return after 2+ weeks away', rarity: AchievementRarity.rare, stardustReward: 25, group: 'Recovery', criteria: AchievementCriteria(customCheck: 'comeback_14')),
    AchievementDef(id: 'R14', name: 'Self-Compassion', description: 'Skip a habit as rest day 5 times', rarity: AchievementRarity.common, stardustReward: 5, group: 'Recovery', criteria: AchievementCriteria(customCheck: 'rest_skips_5')),
    AchievementDef(id: 'R15', name: 'Wisdom of the Drift', description: 'Write a reflection note after returning', rarity: AchievementRarity.epic, stardustReward: 100, group: 'Recovery', criteria: AchievementCriteria(customCheck: 'drift_reflection')),

    // ---- EXPLORATION (25) ----
    AchievementDef(id: 'X1', name: 'First Footstep', description: 'Complete onboarding', rarity: AchievementRarity.common, stardustReward: 5, group: 'Exploration', criteria: AchievementCriteria(customCheck: 'onboarded')),
    AchievementDef(id: 'X2', name: 'Cartographer', description: 'Visit the Stats screen', rarity: AchievementRarity.common, stardustReward: 5, group: 'Exploration', criteria: AchievementCriteria(customCheck: 'visited_stats')),
    AchievementDef(id: 'X3', name: 'Astronomer', description: 'Visit the Cosmos screen', rarity: AchievementRarity.common, stardustReward: 5, group: 'Exploration', criteria: AchievementCriteria(customCheck: 'visited_cosmos')),
    AchievementDef(id: 'X4', name: 'Stargazer', description: 'View a constellation', rarity: AchievementRarity.rare, stardustReward: 25, group: 'Exploration', criteria: AchievementCriteria(customCheck: 'viewed_constellation')),
    AchievementDef(id: 'X5', name: 'Constellation Hunter', description: 'Complete a constellation', rarity: AchievementRarity.epic, stardustReward: 100, group: 'Exploration', criteria: AchievementCriteria(customCheck: 'constellation_complete')),
    AchievementDef(id: 'X6', name: 'Sky Chart Complete', description: 'Complete all constellations', rarity: AchievementRarity.legendary, stardustReward: 250, group: 'Exploration', criteria: AchievementCriteria(customCheck: 'all_constellations')),
    AchievementDef(id: 'X7', name: 'Color Theorist', description: 'Try 3 different palettes', rarity: AchievementRarity.common, stardustReward: 5, group: 'Exploration', criteria: AchievementCriteria(customCheck: 'palettes_3')),
    AchievementDef(id: 'X8', name: 'Painter', description: 'Try 8 different palettes', rarity: AchievementRarity.rare, stardustReward: 25, group: 'Exploration', criteria: AchievementCriteria(customCheck: 'palettes_8')),
    AchievementDef(id: 'X9', name: 'Composer', description: 'Try a non-default sound pack', rarity: AchievementRarity.common, stardustReward: 5, group: 'Exploration', criteria: AchievementCriteria(customCheck: 'sound_changed')),
    AchievementDef(id: 'X10', name: 'Silent Voyager', description: 'Use the app with sound off for 30 days', rarity: AchievementRarity.common, stardustReward: 5, group: 'Exploration', criteria: AchievementCriteria(customCheck: 'silent_30')),
    AchievementDef(id: 'X11', name: 'Tactile Soul', description: 'Use haptics for 30 days', rarity: AchievementRarity.common, stardustReward: 5, group: 'Exploration', criteria: AchievementCriteria(customCheck: 'haptic_30')),
    AchievementDef(id: 'X12', name: 'Reduced Motion', description: 'Use reduced motion mode', rarity: AchievementRarity.common, stardustReward: 5, group: 'Exploration', criteria: AchievementCriteria(customCheck: 'reduce_motion')),
    AchievementDef(id: 'X13', name: 'Custom Icon', description: 'Change the app icon', rarity: AchievementRarity.rare, stardustReward: 25, group: 'Exploration', criteria: AchievementCriteria(customCheck: 'icon_changed')),
    AchievementDef(id: 'X14', name: 'Widget Wielder', description: 'Add a home screen widget', rarity: AchievementRarity.rare, stardustReward: 25, group: 'Exploration', criteria: AchievementCriteria(customCheck: 'widget_added')),
    AchievementDef(id: 'X15', name: 'Watch Companion', description: 'Use the watch companion', rarity: AchievementRarity.rare, stardustReward: 25, group: 'Exploration', criteria: AchievementCriteria(customCheck: 'watch_used')),
    AchievementDef(id: 'X16', name: 'Spatial Explorer', description: 'Use spatial mode (visionOS/XR)', rarity: AchievementRarity.epic, stardustReward: 100, group: 'Exploration', criteria: AchievementCriteria(customCheck: 'spatial_mode')),
    AchievementDef(id: 'X17', name: 'Desktop Voyager', description: 'Use the desktop app', rarity: AchievementRarity.rare, stardustReward: 25, group: 'Exploration', criteria: AchievementCriteria(customCheck: 'desktop_used')),
    AchievementDef(id: 'X18', name: 'Cross-Platform', description: 'Use Gravity Habit on 2+ platforms', rarity: AchievementRarity.epic, stardustReward: 100, group: 'Exploration', criteria: AchievementCriteria(customCheck: 'cross_platform')),
    AchievementDef(id: 'X19', name: 'Locked Down', description: 'Enable app lock', rarity: AchievementRarity.common, stardustReward: 5, group: 'Exploration', criteria: AchievementCriteria(customCheck: 'app_lock')),
    AchievementDef(id: 'X20', name: 'Polyglot', description: 'Change language', rarity: AchievementRarity.rare, stardustReward: 25, group: 'Exploration', criteria: AchievementCriteria(customCheck: 'language_changed')),
    AchievementDef(id: 'X21', name: 'Quest Hunter', description: 'Complete 10 daily quests', rarity: AchievementRarity.common, stardustReward: 5, group: 'Exploration', criteria: AchievementCriteria(questsCompleted: 10)),
    AchievementDef(id: 'X22', name: 'Quest Seeker', description: 'Complete 50 daily quests', rarity: AchievementRarity.rare, stardustReward: 25, group: 'Exploration', criteria: AchievementCriteria(questsCompleted: 50)),
    AchievementDef(id: 'X23', name: 'Quest Master', description: 'Complete 100 daily quests', rarity: AchievementRarity.epic, stardustReward: 100, group: 'Exploration', criteria: AchievementCriteria(questsCompleted: 100)),
    AchievementDef(id: 'X24', name: 'Quest Legend', description: 'Complete 365 daily quests', rarity: AchievementRarity.legendary, stardustReward: 250, group: 'Exploration', criteria: AchievementCriteria(questsCompleted: 365)),
    AchievementDef(id: 'X25', name: 'Quest Eternal', description: 'Complete 1000 daily quests', rarity: AchievementRarity.mythic, stardustReward: 1000, group: 'Exploration', criteria: AchievementCriteria(questsCompleted: 1000)),

    // ---- MASTERY (35) ----
    AchievementDef(id: 'M1', name: 'Resonance', description: 'Complete 2 linked habits within 2 hours', rarity: AchievementRarity.common, stardustReward: 5, group: 'Mastery', criteria: AchievementCriteria(customCheck: 'resonance_2')),
    AchievementDef(id: 'M2', name: 'Harmonic', description: 'Complete 3 linked habits within 2 hours', rarity: AchievementRarity.rare, stardustReward: 25, group: 'Mastery', criteria: AchievementCriteria(customCheck: 'resonance_3')),
    AchievementDef(id: 'M3', name: 'Symphony', description: 'Complete 4+ linked habits within 2 hours', rarity: AchievementRarity.epic, stardustReward: 100, group: 'Mastery', criteria: AchievementCriteria(customCheck: 'resonance_4')),
    AchievementDef(id: 'M4', name: 'Crescendo', description: 'Achieve resonance 50 times', rarity: AchievementRarity.legendary, stardustReward: 250, group: 'Mastery', criteria: AchievementCriteria(customCheck: 'resonance_50x')),
    AchievementDef(id: 'M5', name: 'Conductor', description: 'Achieve resonance 200 times', rarity: AchievementRarity.mythic, stardustReward: 1000, group: 'Mastery', criteria: AchievementCriteria(customCheck: 'resonance_200x')),
    AchievementDef(id: 'M6', name: 'Tier Five', description: 'Reach Tier 5', rarity: AchievementRarity.common, stardustReward: 5, group: 'Mastery', criteria: AchievementCriteria(tier: 5)),
    AchievementDef(id: 'M7', name: 'Tier Ten', description: 'Reach Tier 10', rarity: AchievementRarity.common, stardustReward: 5, group: 'Mastery', criteria: AchievementCriteria(tier: 10)),
    AchievementDef(id: 'M8', name: 'Asteroid Era', description: 'Enter Era II', rarity: AchievementRarity.rare, stardustReward: 25, group: 'Mastery', criteria: AchievementCriteria(tier: 10)),
    AchievementDef(id: 'M9', name: 'Lunar Era', description: 'Enter Era III', rarity: AchievementRarity.rare, stardustReward: 25, group: 'Mastery', criteria: AchievementCriteria(tier: 25)),
    AchievementDef(id: 'M10', name: 'Planetary Era', description: 'Enter Era IV', rarity: AchievementRarity.epic, stardustReward: 100, group: 'Mastery', criteria: AchievementCriteria(tier: 45)),
    AchievementDef(id: 'M11', name: 'Stellar Era', description: 'Enter Era V', rarity: AchievementRarity.epic, stardustReward: 100, group: 'Mastery', criteria: AchievementCriteria(tier: 65)),
    AchievementDef(id: 'M12', name: 'Quasar Era', description: 'Enter Era VI', rarity: AchievementRarity.legendary, stardustReward: 250, group: 'Mastery', criteria: AchievementCriteria(tier: 85)),
    AchievementDef(id: 'M13', name: 'Gravity Itself', description: 'Reach Tier 100', rarity: AchievementRarity.mythic, stardustReward: 1000, group: 'Mastery', criteria: AchievementCriteria(tier: 100)),
    AchievementDef(id: 'M14', name: 'Prestige I', description: 'Prestige for the first time', rarity: AchievementRarity.mythic, stardustReward: 1000, group: 'Mastery', criteria: AchievementCriteria(prestigeLevel: 1)),
    AchievementDef(id: 'M15', name: 'Prestige III', description: 'Prestige three times', rarity: AchievementRarity.mythic, stardustReward: 1000, group: 'Mastery', criteria: AchievementCriteria(prestigeLevel: 3)),
    AchievementDef(id: 'M16', name: 'Prestige VII', description: 'Prestige seven times', rarity: AchievementRarity.mythic, stardustReward: 1000, group: 'Mastery', criteria: AchievementCriteria(prestigeLevel: 7)),
    AchievementDef(id: 'M17', name: 'Stardust Saver', description: 'Collect 500 Stardust', rarity: AchievementRarity.common, stardustReward: 5, group: 'Mastery', criteria: AchievementCriteria(stardustCollected: 500)),
    AchievementDef(id: 'M18', name: 'Stardust Hoarder', description: 'Collect 5000 Stardust', rarity: AchievementRarity.rare, stardustReward: 25, group: 'Mastery', criteria: AchievementCriteria(stardustCollected: 5000)),
    AchievementDef(id: 'M19', name: 'Stardust Lord', description: 'Collect 25000 Stardust', rarity: AchievementRarity.epic, stardustReward: 100, group: 'Mastery', criteria: AchievementCriteria(stardustCollected: 25000)),
    AchievementDef(id: 'M20', name: 'Cosmic Wealth', description: 'Collect 100000 Stardust', rarity: AchievementRarity.legendary, stardustReward: 250, group: 'Mastery', criteria: AchievementCriteria(stardustCollected: 100000)),
    AchievementDef(id: 'M21', name: 'Generous Self', description: 'Spend Stardust for the first time', rarity: AchievementRarity.common, stardustReward: 5, group: 'Mastery', criteria: AchievementCriteria(customCheck: 'first_purchase')),
    AchievementDef(id: 'M22', name: 'Curator', description: 'Own 5 cosmetics', rarity: AchievementRarity.rare, stardustReward: 25, group: 'Mastery', criteria: AchievementCriteria(customCheck: 'cosmetics_5')),
    AchievementDef(id: 'M23', name: 'Collector', description: 'Own 20 cosmetics', rarity: AchievementRarity.epic, stardustReward: 100, group: 'Mastery', criteria: AchievementCriteria(customCheck: 'cosmetics_20')),
    AchievementDef(id: 'M24', name: 'Completionist', description: 'Own all cosmetics', rarity: AchievementRarity.legendary, stardustReward: 250, group: 'Mastery', criteria: AchievementCriteria(customCheck: 'cosmetics_all')),
    AchievementDef(id: 'M25', name: 'Mindful', description: 'Log mood 10 times', rarity: AchievementRarity.common, stardustReward: 5, group: 'Mastery', criteria: AchievementCriteria(moodLogs: 10)),
    AchievementDef(id: 'M26', name: 'Reflective', description: 'Log mood 100 times', rarity: AchievementRarity.rare, stardustReward: 25, group: 'Mastery', criteria: AchievementCriteria(moodLogs: 100)),
    AchievementDef(id: 'M27', name: 'Inner Cartographer', description: 'Log mood 365 times', rarity: AchievementRarity.epic, stardustReward: 100, group: 'Mastery', criteria: AchievementCriteria(moodLogs: 365)),
    AchievementDef(id: 'M28', name: 'Self-Witness', description: 'Log mood 1000 times', rarity: AchievementRarity.legendary, stardustReward: 250, group: 'Mastery', criteria: AchievementCriteria(moodLogs: 1000)),
    AchievementDef(id: 'M29', name: 'Note-Taker', description: 'Write 10 completion notes', rarity: AchievementRarity.common, stardustReward: 5, group: 'Mastery', criteria: AchievementCriteria(notesWritten: 10)),
    AchievementDef(id: 'M30', name: 'Journal Keeper', description: 'Write 100 completion notes', rarity: AchievementRarity.rare, stardustReward: 25, group: 'Mastery', criteria: AchievementCriteria(notesWritten: 100)),
    AchievementDef(id: 'M31', name: 'Memoir of Orbits', description: 'Write 365 completion notes', rarity: AchievementRarity.epic, stardustReward: 100, group: 'Mastery', criteria: AchievementCriteria(notesWritten: 365)),
    AchievementDef(id: 'M32', name: 'Sharer', description: 'Share a card for the first time', rarity: AchievementRarity.common, stardustReward: 5, group: 'Mastery', criteria: AchievementCriteria(customCheck: 'first_share')),
    AchievementDef(id: 'M33', name: 'Anniversary', description: 'Use the app for 1 year', rarity: AchievementRarity.rare, stardustReward: 25, group: 'Mastery', criteria: AchievementCriteria(daysInstalled: 365)),
    AchievementDef(id: 'M34', name: 'Double Anniversary', description: 'Use the app for 2 years', rarity: AchievementRarity.epic, stardustReward: 100, group: 'Mastery', criteria: AchievementCriteria(daysInstalled: 730)),
    AchievementDef(id: 'M35', name: 'Founding User', description: 'Install within the first year of launch', rarity: AchievementRarity.legendary, stardustReward: 250, group: 'Mastery', criteria: AchievementCriteria(customCheck: 'founding_user')),
  ];

  static List<AchievementDef> byGroup(String group) =>
      all.where((a) => a.group == group).toList();

  static const groups = [
    'Consistency',
    'Variety',
    'Endurance',
    'Recovery',
    'Exploration',
    'Mastery',
  ];
}
